nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        tags:
            - name: Gender
              description: Endpoints related to genders
            - name: Player
              description: Endpoints related to players
            - name: PlayerProperty
              description: Endpoints related to properties
            - name: PlayerPropertyValue
              description: Endpoints related to property values
            - name: Game
              description: Endpoints related to games
            - name: Tournament
              description: Endpoints related to tournaments
    areas:
        path_patterns:
            - ^/api(?!/doc$)